export const SELECT_HERO = 'SELECT_HERO';
export const FETCH_HEROES = 'FETCH_HEROES';
export const ADD_TO_SCROREBOARD = 'ADD_TO_SCROREBOARD';
export const FETCH_SEARCH_HEROES = 'FETCH_SEARCH_HEROES';
